---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/luanti.ch
  tasks:
    - name: Checkout git main
      ansible.builtin.git:
        repo: https://github.com/luanti-ch/luanti.ch
        dest: "{{ compose_directory }}"
        single_branch: yes
        force: yes
        version: main

    - name: Create and start services
      shell:
        cmd: "docker-compose up -d --remove-orphans"
        chdir: "{{ compose_directory }}"

    - name: Reload nginx config
      shell:
        cmd: "docker-compose exec -T nginx nginx -s reload"
        chdir: "{{ compose_directory }}"