---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/minetest.ch
  tasks:
    - name: Checkout git master
      ansible.builtin.git:
        repo: https://github.com/BuckarooBanzay/minetest.ch
        dest: "{{ compose_directory }}"
        single_branch: yes
        force: yes
        version: master

    - name: Template docker-compose
      template:
        src: "docker-compose.yml"
        dest: "{{compose_directory}}/docker-compose.yml"

    - name: Create and start services
      community.general.docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        build: yes
        remove_orphans: yes

    - name: Reload nginx config
      shell:
        cmd: "docker-compose exec -T nginx nginx -s reload"
        chdir: "{{ compose_directory }}"