version: "2"

services:
 nginx:
  image: nginx:1.25.2
  networks:
   - terminator
   - default
  restart: always
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.luanti-ch.rule=Host(`luanti.ch`)"
    - "traefik.http.services.luanti-ch.loadbalancer.server.port=80"
    - "traefik.http.routers.luanti-ch.entrypoints=websecure"
    - "traefik.http.routers.luanti-ch.tls.certresolver=default"
  volumes:
   - "./nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./site/public:/html"

 redirect:
  image: nginx:1.25.2
  networks:
   - terminator
   - default
  restart: always
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.minetest-ch.rule=Host(`minetest.ch`)"
    - "traefik.http.services.minetest-ch.loadbalancer.server.port=80"
    - "traefik.http.routers.minetest-ch.entrypoints=websecure"
    - "traefik.http.routers.minetest-ch.tls.certresolver=default"
  volumes:
   - "./redirect.conf:/etc/nginx/conf.d/default.conf:ro"

 hugo:
  image: hugomods/hugo:reg-ci-0.140.2
  restart: "no"
  working_dir: /site
  volumes:
   - "./site:/site"
  command: "build --baseURL https://luanti.ch/"


networks:
 terminator:
  external: true
