baseURL = 'https://luanti.ch/'
languageCode = 'en-us'
title = 'luanti.ch'

# https://themes.gohugo.io/themes/hyde/
# https://gohugo.io/content-management/organization/

[Menus]
  main = [
    {Name = "Hosting", URL = "/pages/hosting"},
    {Name = "Github", URL = "https://github.com/luanti-ch"}
  ]

[params]
  description = "luanti.ch startpage"
  themeColor = "theme-base-09"